{{ if .Values.apps }}{{ if .Values.apps.openmrs }} {{ if .Values.apps.openmrs.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: openmrs-configs
  labels:
    app: openmrs
data:
  OPENMRS_DB_NAME: openmrs
  OPENMRS_USER: superman
  OPENMRS_PASSWORD: Admin123
  OPENMRS_HOST: openmrs
  OPENMRS_DB_USER: openmrs
  OPENMRS_DB_HOST: mysql
  OPENMRS_DB_PASSWORD: password
  OPENMRS_OWAS_PATH: openmrs_core
  OPENMRS_MODULES_PATH: openmrs_modules
  OPENMRS_CONFIG_PATH: openmrs_config
  OPENMRS_CONFIG_CHECKSUMS_PATH: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openmrs-props
  labels:
    app: openmrs
data:
  erp.properties: |
    erp.host=${ODOO_HOST}
    erp.port=8069
    erp.user=${ODOO_USER}
    erp.password=${ODOO_PASSWORD}
    erp.database=${ODOO_DB}

  bahmnicore.properties: |
    bahmnicore.images.directory=/home/bahmni/patient_images
    bahmnicore.images.directory.defaultImage=/home/bahmni/patient_images/blank-user.png
    bahmnicore.urls.patientimages=/patient_images
    bahmnicore.documents.baseDirectory=/home/bahmni/document_images

    feed.maxFailedEvents=10000
    feed.connectionTimeoutInMilliseconds=10000
    feed.replyTimeoutInMilliseconds=20000

    openelis.uri=http://openelis:8080/
    openelis.user={{ .Values.apps.openelis.OPENELIS_ATOMFEED_USER }}
    openelis.password={{ .Values.apps.openelis.OPENELIS_ATOMFEED_PASSWORD }}
    patient.feed.uri=http://openelis:8080/openelis/ws/feed/patient/recent

{{ end }}{{ end }}{{ end }}
