{{ if .Values.apps }}{{ if .Values.apps.backup_services }} {{ if .Values.apps.backup_services.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: create-backup-folder
data:
  create_backup_folder.sh: |
    #!/bin/bash
    set -eu
    FOLDER_NAME=`date +"%Y-%m-%d_%H-%M"`
    mkdir -p /opt/backup/$folder_name

    # Point to the internal API server hostname
    APISERVER=https://kubernetes.default.svc

    # Path to ServiceAccount token
    SERVICEACCOUNT=/var/run/secrets/kubernetes.io/serviceaccount

    # Read this Pod's namespace
    NAMESPACE=$(cat ${SERVICEACCOUNT}/namespace)

    # Read the ServiceAccount bearer token
    TOKEN=$(cat ${SERVICEACCOUNT}/token)

    # Reference the internal certificate authority (CA)
    CACERT=${SERVICEACCOUNT}/ca.crt

    # Update the config map
    curl --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X PUT ${APISERVER}/api/v1/namespaces/backup/configmaps -d '{"apiVersion": "v1", "kind": "ConfigMap", "metadata": { "name": "backup_folder_name"}, "data": { "FOLDER_NAME": "$FOLDER_NAME"}}'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup_folder_name
data:
  FOLDER_NAME: date
{{ end }}{{ end }}{{ end }}